### ISSUE TITLE
Reacts on commands within sentences

### ISSUE THREAD

**Issue by dukemadcat** [League-of-Foundry-Developers/Chat-Commands-Lib#11]
First of all: Great library!!!

Commands are recognized even if they are not at the beginning of a chatmessage.

For example I implemented a command to show images from urls in chat which I called `/img`.

As one player tried to share a video on `https://imgur.com` but it did not work because the /img in this url was also recognized.

It would be great if a command only works if it starts the sentence 😅 Maybe only of the command starts with an "/" or an configuable character.

**Comment by cswendrowski** [comment]
Closed as of latest version
