### ISSUE TITLE
FoundryVTT page now lists beta-1.0.0 as the latest

### ISSUE THREAD

**Issue by MrVauxs** [League-of-Foundry-Developers/Chat-Commands-Lib#18]
![image](https://user-images.githubusercontent.com/32039708/215339911-68959988-59c6-41b5-aa63-465557df9655.png)

**Comment by cs96and** [comment]
I keep getting this popup when updating my modules too...
![image](https://user-images.githubusercontent.com/898086/215772834-6262d807-191b-45bd-9248-997e9b51becb.png)

**Comment by MrVauxs** [comment]
This turned out being an issue on Foundry's website. Should be fixed tonight.
