### ISSUE TITLE
Incompatibility with Dice Tray module

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/Chat-Commands-Lib#3]
Chat Commands doesn't look nice with modules that add bottom padding to the chat.

In example with [Dice Tray](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator) module we can clearly see chatghosttextarea under UI from Dice Tray and because of that the UI is unreadable.

![obraz](https://user-images.githubusercontent.com/15898113/107893399-42355380-6f2b-11eb-87dd-724a724b20bb.png)

**Comment by DevCaua** [comment]
I second this one. Maybe a setting toggle to hide that bottom chat box?

**Comment by cswendrowski** [comment]
Fixed as of 1.3.0
