### ISSUE TITLE
Not reporting for ChatMessage created by API and Macro

### ISSUE THREAD

**Issue by flamewave000** [League-of-Foundry-Developers/Chat-Commands-Lib#6]
A user reported an issue to my DF Chat Enhancements module that they are trying to use a Macro to create a Chat Message via my registered Chat Command `/log`. Apparently this is not being caught by Chat Commands and is instead printing directly to the Chat Log.

You can find their issue here: [DF Chat Enhancement: Issue #81](https://github.com/flamewave000/dragonflagon-fvtt/issues/81)

**Comment by cswendrowski** [comment]
Howdy @flamewave000 - I took a look into this, and when creating a ChatMessage via macro, the `chatMessage` hook is skipped, going straight to `createChatMessage`, a hook that lacks the same info. Adding support for parsing this would break any commands that used data missing in `createChatMessage` such as the chatLog html.

This should likely bubble up further to a Core issue - I'm not sure why `ChatMessage.Create` is skipping that first hook

**Comment by flamewave000** [comment]
Thanks for looking into it. I plan to expose my Adventure Log API so they can access it directly in a Macro any way. That way they can avoid this issue and also write a simpler macro, so no worries!
