### ISSUE TITLE
v1.3.1 duplicates messages in chat

### ISSUE THREAD

**Issue by brother-oak** [League-of-Foundry-Developers/Chat-Commands-Lib#7]
I've just updated to the latest version 1.3.1 to test out the autocomplete whisper compatibility.

I'm now getting every message repeated twice in the chat. This happens even when I don't have autocomplete whisper or DF Chat Enhancements enabled - i.e. it happens with Chat-Commands-Lib enabled and doesn't happen when it isnt.

(Note that I found this behaviour myself when I only removed ONE of the bindings, and not both, in my workaround for Issue #5 - I had to remove BOTH bindings for the incompatibility to be resolved, and for there not to be duplicate messages)

**Comment by cswendrowski** [comment]
If I remove the second binding, then autocomplete for Chat Commands no longer works. Unfortunately, both modules are competing for the same keybinds - I'm not sure how to resolve this.

For now, I'm going to revert the changes make to 1.3.1 to remove the double-send. If we can find a solution for Autocomplete to work in both modules, that'd be awesome

**Comment by shinkei13** [comment]
I was able to get both modules playing nicely by adding this code to line 207 (just after the handler for "#command-menu", but within function jumpToMenuHandler(e):
```
            if (game.modules.get("autocomplete-whisper") != undefined) {
                if ($("#whisper-menu").find("li").length) {
                    if (e.which === 38) { // `up`
                        $("#whisper-menu li:last-child").focus();
                        return false;
                    } else if (e.which === 40) { // `down`
                        $("#whisper-menu li:first-child").focus();
                        return false;
                    }
                }
            }
```
